[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.61.0"
RUBY_VERSION = "2.6.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.61.0"

[[redirects]]
  from = "/classes/dig-deep"
  to = "/dig-deep"
  status = 301
  force = true

[[redirects]]
  from = "/classes/sacred-service"
  to = "/sacred-service"
  status = 301
  force = true

[[redirects]]
  from = "https://sacredspace.netlify.app/*"
  to = "https://sacredspaceyogi.com/:splat"
  status = 301
  force = true